name: crs_revamp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  dio: ^5.4.0
  fluttertoast: ^8.2.9
  shared_preferences: ^2.2.2
  flutter_plugin_android_lifecycle: ^2.0.1
  image: ^4.1.3
  pinput: ^3.0.1
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  path_provider: ^2.0.15
  pdf: ^3.10.8
  printing: ^5.12.0
  share_plus: ^7.2.1
  permission_handler: ^11.4.0
  local_auth: ^2.3.0
  http: ^0.13.6
  open_filex: ^4.0.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.6
  onesignal_flutter: ^5.3.3
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
