name: crs_revamp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  dio: ^5.4.0
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.2
  flutter_plugin_android_lifecycle: ^2.0.1
  image: ^4.1.3
  pinput: ^3.0.1
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  path_provider: ^2.0.15
  pdf: ^3.10.8
  share_plus: ^9.0.0
  permission_handler: ^11.4.0
  local_auth: ^2.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
